spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/Login?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 960930
